const dbQuestionsData = `
DB|A database is an organized, persistent collection of related data that models some aspect of the real world.|True|False|Cannot be determined|A|A database must be organized (defined structure), persistent (survives after the program stops), and related (data items connect in meaningful ways). All three words in the definition are critical.
DB|"Persistent" in the definition of a database means the data is encrypted and secure.|True|False|Cannot be determined|B|FALSE — "Persistent" means the data SURVIVES after the program that created it stops running. It refers to durability, not security. Security is a separate DBMS function.
DB|File-based systems cause exactly three problems: redundancy, inconsistency, and poor security.|True|False|Cannot be determined|B|FALSE — File-based systems cause SIX problems: (1) Data Redundancy, (2) Data Inconsistency, (3) Data Isolation, (4) Integrity Problems, (5) Concurrent Access issues, and (6) Poor Security.
DB|Data Inconsistency in file-based systems occurs when the same fact is stored in multiple files by different departments.|True|False|Cannot be determined|B|FALSE — That describes Data REDUNDANCY. Data INCONSISTENCY occurs when updates in one file are not reflected in others, causing the same entity to have different values across different systems.
DB|A DBMS provides six core functions: definition, manipulation, sharing, security, integrity, and backup/recovery.|True|False|Cannot be determined|A|These are exactly the six core functions. DDL for definition, DML for manipulation, concurrent access for sharing, GRANT/REVOKE for security, constraints for integrity, and WAL for backup/recovery.
DB|Write-Ahead Logging (WAL) ensures that no committed transaction is ever lost, even on sudden power failure.|True|False|Cannot be determined|A|WAL is the technique used by DBMS systems to guarantee durability — part of the Backup and Recovery function. Before any data page is changed on disk, the change is first written to the log.
DB|The ANSI/SPARC Three-Level Architecture was proposed in 1975 and defines three levels: External, Conceptual, and Internal.|True|False|Cannot be determined|A|The ANSI/SPARC committee proposed this standard model in 1975. The three levels are: External (user views), Conceptual (full logical schema), and Internal (physical storage layout).
DB|Physical Data Independence means you can change the logical schema without breaking existing application views.|True|False|Cannot be determined|B|FALSE — That describes LOGICAL data independence. PHYSICAL data independence means you can change how data is stored on disk (add an index, change page size) without rewriting any application code.
DB|E.F. Codd published the relational model paper in 1970 and received the Turing Award in 1981.|True|False|Cannot be determined|A|Edgar F. Codd published "A Relational Model of Data for Large Shared Data Banks" in Communications of the ACM in June 1970. He received the Turing Award in 1981 for this foundational work.
DB|End Users in a database system typically write SQL directly to interact with the data.|True|False|Cannot be determined|B|FALSE — End Users are non-technical users who interact through web forms and applications. They NEVER write SQL directly. Application Programmers write the SQL embedded in the apps that end users use.
DB|Which of the six file-based system problems occurs when two programs write the same file simultaneously and corrupt data?|Data Redundancy|Concurrent Access|Data Isolation|B|Concurrent Access is the problem where two programs writing the same file at the same time cause race conditions and corrupt records. A DBMS solves this with transaction management and locking.
DB|Which DBMS function uses the commands CREATE, ALTER, and DROP?|DML — Data Manipulation Language|DCL — Data Control Language|DDL — Data Definition Language|C|DDL (Data Definition Language) is used to define and modify database STRUCTURE: create tables, define data types, set constraints, create indexes and views. Commands: CREATE, ALTER, DROP.
DB|What does the External Level of the ANSI/SPARC architecture contain?|The full logical schema with all tables, columns, and FK relationships|Individual user views and application-specific subsets of the data|Physical storage layout including B+Tree index files and page sizes|B|The External Level is what individual users and apps see — each user gets a tailored view. Example: A student sees only their own grades; Finance sees tuition data, not academic records.
DB|Which database user category is responsible for installing the DBMS, creating accounts, granting permissions, monitoring performance, and managing backups?|Application Programmer|System Analyst|Database Administrator (DBA)|C|The DBA handles all operational aspects: schema management, user administration, performance tuning, backup management, high availability, security auditing, and capacity planning.
DB|Which data model uses tables with rows and columns and was introduced by E.F. Codd in 1970?|Hierarchical Model|Network Model|Relational Model|C|The Relational Model proposed by E.F. Codd in 1970 uses tables (relations) with rows (tuples) and columns (attributes). It has been the dominant database model for over 50 years.
DB|Which data model is best suited for highly connected data such as social networks and fraud detection?|Document Model (JSON/BSON)|Graph Model (nodes and edges)|Key-Value Model (dictionary)|B|The Graph Model uses nodes and edges to represent data and relationships. Systems like Neo4j and Amazon Neptune are optimized for traversing highly connected data, making them ideal for social networks and fraud detection.
DB|The NoSQL revolution happened primarily in which era?|1970s–80s|1990s–00s|2000s–10s|C|The NoSQL Revolution occurred in the 2000s–2010s with the rise of MongoDB, Cassandra, and Redis to handle Big Data and horizontal scaling needs that traditional RDBMS systems struggled with.
DB|Which SQL category includes COMMIT, ROLLBACK, and SAVEPOINT?|DDL — Data Definition Language|DML — Data Manipulation Language|TCL — Transaction Control Language|C|TCL (Transaction Control Language) manages transactions and data consistency. COMMIT makes changes permanent, ROLLBACK undoes them, SAVEPOINT creates a point to roll back to. Covered in Chapter 7.
DB|Data Isolation as a file-based problem means that data is scattered across incompatible file formats, making cross-department queries impossible.|True|False|Cannot be determined|A|Data Isolation occurs when data is scattered across incompatible formats (CSV, binary, XML) managed by different programs. It becomes impossible to run a single query that combines data from all sources.
DB|Logical Data Independence is harder to achieve than Physical Data Independence.|True|False|Cannot be determined|A|Logical Data Independence (adding tables/columns without breaking existing views) is harder because views depend on the logical structure. Physical changes (adding an index) don't change what data means, so they're easier to hide from applications.
DB|In Chen notation, a strong entity is represented by which symbol?|A diamond shape|A single rectangle|A double oval|B|In Chen notation: Strong entity = single rectangle. Weak entity = double rectangle. Relationship = diamond. Key attribute = underlined oval. Multi-valued attribute = double oval.
DB|A Derived Attribute in an ER diagram is stored physically in the database.|True|False|Cannot be determined|B|FALSE — A Derived Attribute is CALCULATED from other data at query time and is NOT stored. Example: age is derived from birth_date. In Chen notation it is shown with a dashed oval. Storing it would create redundancy.
DB|A Many-to-Many (M:N) relationship between STUDENT and COURSE can be represented with just two tables without a junction table.|True|False|Cannot be determined|B|FALSE — An M:N relationship CANNOT be represented with just two tables in the relational model. You MUST create a third junction (associative) table containing the PKs of both entities as foreign keys, plus any relationship attributes.
DB|Which cardinality type requires creating a junction (associative) table in the relational schema?|One-to-One (1:1)|One-to-Many (1:N)|Many-to-Many (M:N)|C|Only M:N relationships require a junction table. The junction table holds the PKs of both entities as FKs, and its combined PK = (entity1_FK + entity2_FK). Relationship attributes (like grade, semester) become columns in this table.
DB|Total Participation in an ER diagram means that EVERY instance of the entity MUST participate in the relationship.|True|False|Cannot be determined|A|Total Participation (drawn with a double line in Chen notation) means every instance of that entity type must be associated with at least one instance of the related entity. Example: every student must belong to at least one department.
DB|A Weak Entity has its own key attribute that can uniquely identify it without depending on any other entity.|True|False|Cannot be determined|B|FALSE — A Weak Entity CANNOT be uniquely identified by its own attributes alone. It has only a PARTIAL key and depends on a related "identifying entity" for its full identity. Example: DEPENDENT needs employee_id + dependent_name for identification.
DB|Which ER mapping rule applies when converting a Many-to-Many relationship to a relational schema?|Rule 3 — 1:1 Relationship Rule: add FK to total-participation side|Rule 4 — 1:N Relationship Rule: add FK of "one" side to "many" side|Rule 5 — M:N Relationship Rule: create a junction table with FKs to both entities|C|Rule 5 states: For M:N relationships, create a new junction table. It contains the PKs of both entities as foreign keys. These together form the PK (or add a surrogate PK). All relationship attributes become columns in this table.
DB|A Composite Attribute is made of sub-attributes that are each stored separately in the database.|True|False|Cannot be determined|A|A Composite Attribute like full_name is decomposed into its sub-attributes (first_name, middle_name, last_name) which are each stored as separate columns. The composite attribute itself is not stored as a single combined value.
DB|Which ER mapping rule handles multi-valued attributes like phone_numbers?|Create a separate table: entity FK + attribute value, with PK = (entity FK + value)|Add multiple columns to the entity table: phone1, phone2, phone3|Convert to a derived attribute and compute at query time|A|Rule 6 — Multi-valued Attribute Rule: Create a new table containing the entity PK as a FK plus the attribute value. The combined PK = entity FK + attribute value. Example: STUDENT_PHONE(student_id FK, phone_number) with PK = (student_id, phone_number).
DB|The identifying relationship in an ER diagram (double diamond) connects a strong entity to another strong entity.|True|False|Cannot be determined|B|FALSE — An Identifying Relationship (double diamond) connects a WEAK entity to its IDENTIFYING (owner) STRONG entity. The weak entity depends on the strong entity for part of its identity. Example: DEPENDENT —(( HAS ))— EMPLOYEE.
DB|In EER modeling, Specialization is a top-down process where you start with a general entity and identify specialized subclasses.|True|False|Cannot be determined|A|Specialization is top-down: you start with a superclass (like PERSON) and specialize it into subclasses (STUDENT, EMPLOYEE). Generalization is the reverse — bottom-up, combining CAR and TRUCK into VEHICLE.
DB|A Relation in the relational model is formally a set of unique tuples — no two tuples can be identical.|True|False|Cannot be determined|A|A relation is mathematically a SET of tuples. Since sets cannot contain duplicates, no two tuples in a relation can be identical. This is why the PRIMARY KEY constraint is required — it guarantees uniqueness.
DB|The Degree of a relation refers to the number of rows (tuples) it contains.|True|False|Cannot be determined|B|FALSE — The DEGREE of a relation is the number of ATTRIBUTES (columns). The number of rows is called the CARDINALITY. Example: STUDENT(student_id, name, email, gpa, dept_id) has degree 5.
DB|A Superkey is any set of attributes that uniquely identifies all tuples in a relation.|True|False|Cannot be determined|A|A Superkey is ANY set of attributes whose values are unique across all rows. It may include unnecessary attributes. Example: {student_id}, {student_id, name}, {student_id, name, email} are all superkeys — even the redundant ones.
DB|A Candidate Key is a minimal superkey — no attribute can be removed while preserving uniqueness.|True|False|Cannot be determined|A|A Candidate Key is the minimal form of a superkey. Removing any single attribute from a candidate key would cause it to no longer be unique. Multiple candidate keys can exist per table.
DB|A Primary Key can contain NULL values as long as they are unique.|True|False|Cannot be determined|B|FALSE — A PRIMARY KEY can NEVER be NULL. This is the Entity Integrity constraint. Every row must be uniquely identifiable. A NULL PK would mean "a row with unknown identity," making it impossible to reference or enforce uniqueness.
DB|Which key type is an artificial auto-increment integer created purely for database identification purposes?|Natural Key|Alternate Key|Surrogate Key|C|A Surrogate Key is an artificial, auto-generated key (like AUTO_INCREMENT in MySQL). It is stable, simple, always available, and never changes — unlike Natural Keys which are derived from real-world data and can change.
DB|The Referential Integrity constraint states that a Foreign Key value must either match an existing Primary Key value in the referenced table, or be NULL.|True|False|Cannot be determined|A|Referential Integrity ensures that FK values point to actual existing PK values. If a student has dept_id=99 but no department with ID 99 exists, the insert is REJECTED. NULL is allowed if the FK column permits it (optional relationship).
DB|In SQL three-valued logic, the result of (NULL = NULL) is TRUE.|True|False|Cannot be determined|B|FALSE — In SQL's three-valued logic (TRUE, FALSE, UNKNOWN), any comparison involving NULL produces UNKNOWN — not TRUE or FALSE. NULL = NULL is UNKNOWN, not TRUE. Use IS NULL to correctly test for NULL values.
DB|The correct SQL syntax to test if a column value is missing (NULL) is: WHERE phone = NULL|True|False|Cannot be determined|B|FALSE — WHERE phone = NULL ALWAYS returns zero rows because NULL = NULL evaluates to UNKNOWN, not TRUE. The CORRECT syntax is: WHERE phone IS NULL. Similarly, use IS NOT NULL for the opposite check.
DB|What does the CASCADE referential integrity action do when a referenced Primary Key row is deleted?|Block the deletion if any FK row references it (safest choice)|Automatically delete all rows that reference the deleted PK row|Set all FK columns to NULL when the referenced row is deleted|B|CASCADE automatically deletes all child rows that reference the deleted parent row. Use CASCADE when child records are meaningless without the parent — for example, enrollment records when a student is deleted.
DB|Which relational algebra operation filters rows by a condition (equivalent to SQL WHERE clause)?|Projection (π — pi)|Selection (σ — sigma)|Cartesian Product (×)|B|Selection (σ) filters rows based on a condition. Notation: σ(condition)(Relation). SQL equivalent: WHERE clause. Example: σ(gpa>3.0)(STUDENT) returns all rows where gpa > 3.0.
DB|Which relational algebra operation chooses specific columns (equivalent to SQL SELECT col1, col2)?|Selection (σ — sigma)|Union (∪)|Projection (π — pi)|C|Projection (π) selects specific columns from a relation. Notation: π(attr1, attr2)(Relation). SQL equivalent: SELECT col1, col2 FROM table. It eliminates unwanted columns from the result.
DB|The UNION operation in relational algebra requires that both relations R and S be union-compatible — same degree and compatible domains.|True|False|Cannot be determined|A|Union-compatibility is required for UNION, INTERSECTION, and DIFFERENCE. Both relations must have the same number of attributes (degree) with compatible domains. The result contains all rows from R or S with duplicates eliminated.
DB|The DIVISION operation in relational algebra has a direct equivalent keyword in standard SQL.|True|False|Cannot be determined|B|FALSE — There is NO direct SQL syntax for Division (÷). It must be expressed using EXISTS/NOT EXISTS subqueries. Division finds tuples in R related to ALL tuples in S. Example: find students who have completed ALL required courses.
DB|SELECT COUNT(*) and SELECT COUNT(grade) from enrollments return the same result when some grades are NULL.|True|False|Cannot be determined|B|FALSE — COUNT(*) counts ALL rows including those with NULL grades. COUNT(grade) counts ONLY rows where grade IS NOT NULL. If any grades are NULL, COUNT(*) will be larger than COUNT(grade). All other aggregate functions (AVG, SUM, MIN, MAX) also ignore NULLs.
DB|What is the correct SQL category for the commands GRANT and REVOKE?|DDL — Data Definition Language|DML — Data Manipulation Language|DCL — Data Control Language|C|DCL (Data Control Language) contains only GRANT and REVOKE. GRANT gives permissions to users; REVOKE removes them. This provides fine-grained access control at the table, column, and row level.
DB|In SQL, DECIMAL(3,2) can correctly store the value 4.00 (a maximum GPA).|True|False|Cannot be determined|A|DECIMAL(3,2) means 3 total digits with 2 decimal places. So valid range is -9.99 to 9.99. The value 4.00 uses 3 digits total (4, 0, 0) which fits within the 3-digit limit. This is why gpa DECIMAL(3,2) CHECK(gpa BETWEEN 0.00 AND 4.00) works correctly.
DB|Which SQL data type should NEVER be used for storing money or GPA values?|DECIMAL(p,s)|INT|FLOAT / DOUBLE|C|FLOAT and DOUBLE use approximate IEEE 754 floating-point storage. For example, 0.1 + 0.2 returns 0.30000000000000004 due to binary rounding errors. For money and GPA, always use DECIMAL which stores values EXACTLY.
DB|The CHAR(n) data type always uses exactly n bytes of storage, regardless of the actual value length.|True|False|Cannot be determined|A|CHAR(n) is a FIXED-LENGTH type — it always allocates n bytes and pads shorter values with spaces. Use for fixed-length codes like country CHAR(2) or gender CHAR(1). Use VARCHAR(n) for variable-length data like names and emails.
DB|Which data type should you use for a column that stores a university enrollment year like 2024?|DATETIME|TIMESTAMP|YEAR|C|The YEAR type uses only 1 byte and stores 4-digit years from 1901 to 2155. It is the most efficient choice for storing just a year. DATETIME and TIMESTAMP store both date AND time, which is unnecessary for a simple year value.
DB|The CREATE TABLE statement in SQL can encode NOT NULL, UNIQUE, CHECK, and FOREIGN KEY constraints.|True|False|Cannot be determined|A|CREATE TABLE is the primary DDL command for defining the complete schema. It can specify: data types, NOT NULL (required values), UNIQUE (no duplicates), CHECK (value validation rules), PRIMARY KEY, and FOREIGN KEY (referential integrity). All constraint types are supported.
DB|What does the AUTO_INCREMENT attribute do in MySQL?|Requires the user to manually provide a unique ID for each inserted row|Automatically generates the next sequential integer value when a row is inserted|Doubles the previous ID value to create exponentially growing IDs|B|AUTO_INCREMENT automatically generates the next available integer when a new row is inserted and no value is provided for that column. It starts at 1 by default and increments by 1. Used for surrogate primary keys.
DB|TRUNCATE TABLE removes all rows from a table and CAN be rolled back using ROLLBACK.|True|False|Cannot be determined|B|FALSE — In MySQL, TRUNCATE is treated as DDL and CANNOT be rolled back. It also resets AUTO_INCREMENT back to 1. DELETE (with a WHERE clause or without) is DML and CAN be rolled back within a transaction.
DB|What is the difference between DROP TABLE and TRUNCATE TABLE?|DROP removes only the data but keeps the table structure; TRUNCATE removes both|TRUNCATE removes only the data but keeps the structure; DROP removes both the data AND the structure|Both commands do exactly the same thing|B|TRUNCATE removes all DATA from the table but keeps the table structure (columns, constraints, indexes) intact. DROP TABLE removes EVERYTHING — the data, the structure, all indexes, all constraints — the table no longer exists.
DB|The best practice before running an UPDATE or DELETE statement is to first run the equivalent SELECT statement to verify which rows will be affected.|True|False|Cannot be determined|A|Always run SELECT first to see exactly which rows match your WHERE condition before modifying or deleting them. This prevents accidental mass updates or deletions. In MySQL Workbench, SET SQL_SAFE_UPDATES = 1 adds an extra safety check.
DB|Which SQL clause is used to implement pagination — showing records 21-40 on page 2?|WHERE page = 2|ORDER BY page_number|LIMIT 20 OFFSET 20|C|LIMIT 20 OFFSET 20 skips the first 20 rows and returns the next 20. Page 1: LIMIT 20 OFFSET 0. Page 2: LIMIT 20 OFFSET 20. Page 3: LIMIT 20 OFFSET 40. The OFFSET value = (page_number - 1) × page_size.
DB|The LIKE operator in SQL uses % to match any single character and _ to match any sequence of characters.|True|False|Cannot be determined|B|FALSE — It is reversed: % matches ANY sequence of zero or more characters, and _ matches exactly ONE single character. Example: LIKE 'Al%' matches names starting with Al; LIKE '_ali' matches 4-character names ending in ali.
DB|In SQL's logical execution order, the WHERE clause is processed BEFORE the SELECT clause.|True|False|Cannot be determined|A|The SQL logical execution order is: FROM → WHERE → GROUP BY → HAVING → SELECT → DISTINCT → ORDER BY → LIMIT. WHERE is processed early (step 2) while SELECT is processed later (step 5). This is why you cannot use SELECT column aliases in WHERE.
DB|Which operator in SQL efficiently tests whether a column value matches any value in a specified list?|BETWEEN|LIKE|IN|C|The IN operator tests if a value matches any value in a list: WHERE dept_id IN (1, 2, 3). It is more efficient and readable than multiple OR conditions: WHERE dept_id = 1 OR dept_id = 2 OR dept_id = 3.
DB|INSERT INTO ... SELECT ... FROM ... can be used to copy rows from one table into another.|True|False|Cannot be determined|A|Yes — INSERT INTO target_table (col1, col2) SELECT col1, col2 FROM source_table WHERE condition. This is commonly used for archiving: INSERT INTO archive_students SELECT ... FROM students WHERE status = 'graduated'.
DB|What does SET SQL_SAFE_UPDATES = 1 do in MySQL?|Encrypts all UPDATE statements for security|Prevents UPDATE and DELETE statements that do not use a WHERE clause with a key column|Automatically backs up data before every UPDATE|B|With SQL_SAFE_UPDATES = 1, MySQL raises an error if you run UPDATE or DELETE without a WHERE clause that references a key column or primary key. This prevents accidental full-table modifications.
DB|The ENUM data type in MySQL stores only values from a predefined list and uses 1-2 bytes of storage.|True|False|Cannot be determined|A|ENUM is efficient (1-2 bytes) and enforces a controlled vocabulary. Example: status ENUM('active','inactive','graduated') means only these three values are accepted. Any other value causes an error. It is ideal for fields with a fixed set of valid values.
DB|A JOIN in SQL is needed because in a normalized relational database, related data is intentionally distributed across multiple tables.|True|False|Cannot be determined|A|Normalization splits data into separate tables to eliminate redundancy. To query related data together (e.g., student name AND their department name), you must JOIN the tables on their shared key relationship. JOINs are the mechanism that reassembles normalized data.
DB|INNER JOIN returns ALL rows from the left table, including rows that have no matching row in the right table.|True|False|Cannot be determined|B|FALSE — That describes LEFT JOIN. INNER JOIN returns ONLY rows where there is a matching row in BOTH tables. If a student has no enrollment record, they will NOT appear in an INNER JOIN with the enrollments table.
DB|LEFT JOIN returns all rows from the left table and NULL values in the right table columns for rows with no match.|True|False|Cannot be determined|A|LEFT JOIN includes ALL rows from the LEFT table. For left-table rows with no matching right-table row, all right-table columns appear as NULL. This is used to find records with optional relationships, like students who may or may not be enrolled.
DB|The Anti-Join pattern finds rows in the LEFT table that have NO matching row in the RIGHT table.|True|False|Cannot be determined|A|Anti-join pattern: LEFT JOIN the two tables, then add WHERE right_table.id IS NULL. The NULL in the right-table column after a LEFT JOIN means "no match was found," effectively finding rows that exist ONLY in the left table.
DB|What does a NULL value in a right-table column after a LEFT JOIN indicate?|The right table column allows NULL values in its schema|No matching row was found in the right table for that left-table row|The JOIN condition used an incorrect column|B|In a LEFT JOIN result, NULL in a right-table column means the current left-table row had NO matching row in the right table. This is the key insight behind the Anti-Join pattern: WHERE right.id IS NULL finds the unmatched rows.
DB|Which JOIN type returns only rows that have a matching row in BOTH tables?|LEFT JOIN|INNER JOIN|RIGHT JOIN|B|INNER JOIN returns ONLY rows where the JOIN condition is satisfied in both tables simultaneously. It is the most commonly used JOIN type and is equivalent to the relational algebra Equi-Join or Natural Join.
DB|A SELF JOIN joins a table to a DIFFERENT table with the same structure.|True|False|Cannot be determined|B|FALSE — A SELF JOIN joins a table to ITSELF. You use two aliases for the same table (e.g., FROM students a JOIN students b ON ...) to compare rows within the same table. Example: find pairs of students in the same department.
DB|When using SELF JOIN to find pairs of rows, using condition (a.id < b.id) prevents duplicate pairs and self-matching.|True|False|Cannot be determined|A|Without a.id < b.id, you would get (Ali, Nour) AND (Nour, Ali) as two separate rows, plus (Ali, Ali) and (Nour, Nour) as self-matches. The < condition ensures each pair appears only once and a row is never matched with itself.
DB|CROSS JOIN produces every possible combination of rows from two tables (Cartesian Product) with no JOIN condition.|True|False|Cannot be determined|A|CROSS JOIN produces n × m rows where n = rows in left table and m = rows in right table. It is the SQL equivalent of Cartesian Product (×) in relational algebra. Always use with a filter (WHERE) or LIMIT to avoid explosive result sets.
DB|What does the following query do? SELECT s.name FROM students s LEFT JOIN enrollments e ON s.student_id = e.student_id WHERE e.student_id IS NULL|Finds all students who ARE enrolled in at least one course|Finds all students who are NOT enrolled in any course|Finds all enrollments without a matching student|B|This is the Anti-Join pattern. LEFT JOIN produces all students, with NULL in enrollment columns for unmatched students. WHERE e.student_id IS NULL filters to keep ONLY the unmatched rows — students with no enrollment records.
DB|Which SQL JOIN type is the equivalent of a Cartesian Product in relational algebra, pairing every row from one table with every row from another?|INNER JOIN|LEFT JOIN|CROSS JOIN|C|CROSS JOIN produces all combinations: if table A has 100 rows and table B has 200 rows, the result has 100 × 200 = 20,000 rows. In relational algebra notation: A × B. Always limit the result when testing with CROSS JOIN.
DB|A three-table INNER JOIN such as students JOIN enrollments JOIN courses returns only rows where all three tables have matching rows.|True|False|Cannot be determined|A|In a chain of INNER JOINs, the result contains only rows where ALL join conditions are satisfied. A student must have an enrollment record, AND that enrollment must have a matching course record. Unmatched rows from any table are excluded.
DB|The WHERE clause in SQL filters individual rows BEFORE aggregation, while HAVING filters groups AFTER GROUP BY.|True|False|Cannot be determined|A|This is a critical distinction. WHERE is processed BEFORE GROUP BY (step 2 vs step 3 in execution order). HAVING is processed AFTER GROUP BY (step 4). You CANNOT use aggregate functions (COUNT, AVG) in WHERE — only in HAVING.
DB|Which aggregate function counts ALL rows including those with NULL values in the specified column?|COUNT(column_name)|COUNT(DISTINCT column_name)|COUNT(*)|C|COUNT(*) counts ALL rows regardless of NULL values. COUNT(column_name) counts only rows where the column IS NOT NULL. COUNT(DISTINCT column_name) counts unique non-NULL values. The difference matters when columns contain NULLs.
DB|A subquery is a SELECT statement nested inside another SQL statement.|True|False|Cannot be determined|A|A subquery (also called inner query or nested query) is a complete SELECT statement embedded within another SQL statement. It can appear in the WHERE clause (scalar or list), FROM clause (derived table), or SELECT clause (correlated scalar).
DB|A correlated subquery references columns from the outer query and is executed ONCE for the entire outer query.|True|False|Cannot be determined|B|FALSE — A correlated subquery references the outer query's current row and is executed ONCE PER ROW of the outer query. This makes it potentially slow for large datasets. When possible, rewrite correlated subqueries as JOINs for better performance.
DB|A View in SQL contains its own stored copy of data that is updated automatically whenever the base tables change.|True|False|Cannot be determined|B|FALSE — A View is a NAMED STORED QUERY, not a copy of data. It contains no data itself — it runs the underlying query each time it is referenced. Views provide security, simplify complexity, and create stable interfaces without data duplication.
DB|Which advantage of database views allows DBAs to grant access to the view without exposing sensitive base table columns?|Simplicity — encapsulates complex JOINs into one object|Security — hide sensitive columns like salary and national_id from unauthorized users|Stability — shields applications from underlying schema changes|B|Security is a key advantage of views: grant SELECT on the view instead of the base table. This lets you hide columns like national_id, salary, or birth_date from users who should not see them while still giving them access to the data they need.
DB|The HAVING clause can use aggregate functions like COUNT() and AVG(), but the WHERE clause cannot.|True|False|Cannot be determined|A|WHERE filters individual rows and is executed before aggregation — so aggregate functions are not yet available. HAVING filters GROUPS after GROUP BY and CAN use aggregate functions. Using aggregate functions in WHERE causes a SQL error.
DB|Which SQL keyword removes duplicate rows from a SELECT result?|UNIQUE|DISTINCT|DIFFERENT|B|DISTINCT eliminates duplicate rows from the result set. Example: SELECT DISTINCT dept_id FROM students returns each department ID only once, even if many students belong to the same department. It is processed after SELECT in the logical execution order.
DB|In SQL, the EXISTS operator is often faster than IN for large datasets because it stops searching as soon as it finds the first match.|True|False|Cannot be determined|A|EXISTS short-circuits — it returns TRUE as soon as one matching row is found, without scanning the entire subquery result. IN must evaluate the entire subquery result first. For large tables, EXISTS often performs significantly better.
DB|The CASE expression in SQL can only be used in a WHERE clause to filter rows based on conditions.|True|False|Cannot be determined|B|FALSE — CASE can be used in SELECT (computed columns), ORDER BY, GROUP BY, and HAVING. It is most commonly used in SELECT to create conditional computed columns. Example: CASE WHEN gpa >= 3.7 THEN 'A' WHEN gpa >= 3.0 THEN 'B' END AS grade_label.
DB|A derived table (subquery in FROM clause) acts as a temporary virtual table for the duration of the query.|True|False|Cannot be determined|A|When a subquery appears in the FROM clause with an alias — like FROM (SELECT ... FROM ...) AS subq — it acts as a temporary virtual table that exists only during query execution. This allows multi-step calculations that cannot be done in a single level of SQL.
DB|RIGHT JOIN returns all rows from the RIGHT table including rows with no match in the left table.|True|False|Cannot be determined|A|RIGHT JOIN is a mirror of LEFT JOIN. It returns ALL rows from the RIGHT table, and for right-table rows with no matching left-table row, the left-table columns appear as NULL. In practice, most developers prefer LEFT JOIN for consistency.
DB|What does the following SQL do? SELECT d.name FROM departments d LEFT JOIN students s ON d.dept_id = s.dept_id AND s.status = 'active' WHERE s.student_id IS NULL|Lists departments that have at least one active student|Lists departments that have NO active students (anti-join)|Lists all students with their department names|B|The LEFT JOIN with the additional condition (AND s.status = 'active') filters enrollment DURING the join. WHERE s.student_id IS NULL then keeps only departments where no active student matched — departments with zero active students.
DB|In a LEFT JOIN result, you can always filter using WHERE right_table.column = 'some_value' to find rows with matches in the right table.|True|False|Cannot be determined|A|If you add a WHERE condition on a right-table column (not checking for NULL), only rows WHERE the right-table column has a value will be returned. This effectively converts the LEFT JOIN into an INNER JOIN — only matched rows pass the WHERE filter.
DB|The SQL logical execution order is: SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY → LIMIT.|True|False|Cannot be determined|B|FALSE — The correct logical execution order is: FROM → WHERE → GROUP BY → HAVING → SELECT → DISTINCT → ORDER BY → LIMIT. SELECT is processed AFTER FROM and WHERE. This is why column aliases created in SELECT cannot be used in WHERE.
DB|Using table aliases in JOINs (e.g., FROM students s JOIN departments d) is required syntax — SQL will not work without aliases.|True|False|Cannot be determined|B|FALSE — Table aliases are optional but highly recommended for readability, especially in multi-table JOINs. Without aliases, you would need to write the full table name every time: students.first_name instead of s.first_name.
DB|What happens when you JOIN two tables on a column that contains NULL values? For example: ON a.dept_id = b.dept_id where some dept_id values are NULL.|NULL = NULL evaluates to TRUE, so NULL rows are included in the INNER JOIN result|NULL = NULL evaluates to UNKNOWN, so rows with NULL dept_id are NOT included in the INNER JOIN result|NULL values cause a SQL error and the JOIN fails|B|In SQL's three-valued logic, NULL = NULL is UNKNOWN (not TRUE). JOIN conditions only include rows where the condition is TRUE. Therefore, rows where the join column is NULL are EXCLUDED from INNER JOIN results.
DB|Which SQL function concatenates two or more strings together?|SUBSTRING()|UPPER()|CONCAT()|C|CONCAT(str1, str2, ...) joins strings together. Example: CONCAT(first_name, ' ', last_name) AS full_name produces 'Ali Mahmoud'. Other string functions: UPPER(), LOWER(), LENGTH(), TRIM(), SUBSTRING(), REPLACE().
DB|The DATEDIFF(date1, date2) function in MySQL returns the difference between two dates in days.|True|False|Cannot be determined|A|DATEDIFF(date1, date2) returns the number of days between date1 and date2 (date1 - date2). Example: DATEDIFF(NOW(), created_at) AS days_since_reg gives the number of days since a student registered.
DB|CREATE OR REPLACE VIEW updates an existing view's definition without needing to DROP and recreate it.|True|False|Cannot be determined|A|CREATE OR REPLACE VIEW is the recommended way to modify a view. If the view exists, it replaces its definition. If it doesn't exist, it creates it. This is safer than DROP VIEW followed by CREATE VIEW because applications using the view remain unaffected during the replacement.
DB|To find the top student by GPA in EACH department using SQL, which approach is most appropriate?|A simple SELECT with ORDER BY GPA DESC LIMIT 1|A derived table or subquery that calculates MAX(gpa) per dept_id then JOINs back|A CROSS JOIN between students and departments|B|You need GROUP BY dept_id to get the max GPA per department, then JOIN back to the students table to get the student's name. A derived table approach: SELECT s.* FROM students s JOIN (SELECT dept_id, MAX(gpa) AS max_gpa FROM students GROUP BY dept_id) d ON s.dept_id = d.dept_id AND s.gpa = d.max_gpa.
`;