// Data Structures & Algorithms (CS211) Question Bank
// Sources: Sheet 2 (T/F + MCQ) + DS_Lecture_970Part2 Revision Section
// Format: DS|question|optionA|optionB|optionC|correctLetter|explanation

const dsQuestionsData = `
DS|Header files like <iostream> add functionality to C++ programs.|True|False|Cannot be determined|A|#include <iostream> is a preprocessor directive that attaches the standard I/O library before compilation, enabling cout and cin.
DS|The cout object outputs values and prints text to the screen.|True|False|Cannot be determined|A|cout (combined with <<) is the standard output stream object — it sends data to the console.
DS|Variables in C++ can store different data types like int, char, and string.|True|False|Cannot be determined|A|C++ is statically typed but provides many types: int, double, char, bool, string — each for a different kind of data.
DS|Constants are variables that can be changed during program execution.|True|False|Cannot be determined|B|Constants declared with 'const' are FIXED — attempting to change them causes a compile-time error. Example: const int MAX = 100;
DS|cin allows user input from the keyboard into a C++ program.|True|False|Cannot be determined|A|cin (with >>) is the standard input stream. It reads values typed by the user and stores them in variables.
DS|An if statement specifies a block of code to execute when a condition is true.|True|False|Cannot be determined|A|if(condition) { ... } — the block only executes when the boolean condition evaluates to true.
DS|else if allows you to check additional conditions if previous ones are false.|True|False|Cannot be determined|A|else if chains let you test multiple mutually exclusive conditions sequentially — only the first true branch runs.
DS|for loops execute a block of code as long as a condition is true.|True|False|Cannot be determined|B|FALSE — for loops repeat a known, fixed number of iterations. It is the WHILE loop that repeats as long as a condition is true.
DS|Nested loops place a loop inside another loop.|True|False|Cannot be determined|A|A nested loop has an inner loop that completes all its iterations for every single iteration of the outer loop. Common for 2D arrays.
DS|The insertion operator << outputs values; the extraction operator >> gets user input.|True|False|Cannot be determined|A|cout << val sends output; cin >> var receives input. The direction of the arrows shows data flow direction.
DS|A const variable in C++ can be modified after its declaration.|True|False|Cannot be determined|B|const means the value is FIXED at initialization. Any attempt to modify it results in a compile error: cannot assign to variable with const-qualified type.
DS|The for loop is the best choice when you know the exact number of iterations in advance.|True|False|Cannot be determined|A|for(int i=0; i<n; i++) is designed for a known count. Use while when the number of iterations is unknown or condition-driven.
DS|cin >> can read a string that includes spaces between words.|True|False|Cannot be determined|B|FALSE — cin >> stops at the first whitespace. To read a full line including spaces, use getline(cin, str) instead.
DS|C++ arrays use zero-based indexing — the first element is at index 0.|True|False|Cannot be determined|A|int arr[5] has valid indices 0,1,2,3,4. Accessing arr[5] is out of bounds and causes undefined behavior.
DS|sqrt() and other math functions are available in C++ without including any library.|True|False|Cannot be determined|B|FALSE — #include <cmath> is REQUIRED for sqrt(), pow(), abs(), round(), ceil(), floor(), max(), and min().
DS|Method overloading means two functions can share the same name with different parameters.|True|False|Cannot be determined|A|int sum(int,int) and double sum(double,double) are both valid — the compiler selects the correct version based on argument types.
DS|A reference and a pointer in C++ are exactly the same thing.|True|False|Cannot be determined|B|References (int& b=a) are aliases — always bound to one variable, no NULL, no arithmetic. Pointers store addresses and can be NULL, reassigned, and incremented.
DS|Memory allocated with 'new' is automatically freed when the function returns.|True|False|Cannot be determined|B|HEAP memory (new) is MANUALLY managed — you must call delete or delete[]. Stack memory (int x=5) is freed automatically.
DS|In a Linked List, the last node's 'next' pointer must be set to NULL.|True|False|Cannot be determined|A|NULL marks the END of the list. The traversal loop while(temp != NULL) uses this to know when to stop.
DS|An array and a linked list use the same amount of memory per element.|True|False|Cannot be determined|B|FALSE — Array: 4 bytes per int. Linked List node: 4 bytes data + 4-8 bytes pointer = more memory per node.
DS|What does #include <iostream> enable in a C++ program?|Input/output capabilities (cout, cin)|Math functions like sqrt and pow|File handling operations|A|#include <iostream> attaches the I/O stream library which provides cout (output) and cin (input) — essential for any C++ program.
DS|What is the purpose of 'using namespace std;' in C++?|Allows use of standard library names without std:: prefix|Defines a new project namespace|Links the standard template library|A|Without it you would write std::cout and std::cin. The directive lets you write cout and cin directly.
DS|Which of the following is NOT a valid C++ variable type?|int|double|text|C|text is not a C++ keyword. Valid types include int, double, char, bool, string. 'text' would cause a compilation error.
DS|Which syntax correctly prints the value of a variable in C++?|print(myVar)|cout << myVar|console.log(myVar)|B|cout << myVar is the correct C++ output syntax. print() is Python; console.log() is JavaScript.
DS|How do you read user input from the keyboard into a variable in C++?|var input = getInput()|cin >> myVar|myVar << cin|B|cin >> myVar reads from standard input. The >> operator extracts the value and stores it in myVar.
DS|Which of the following are valid comparison/logical operators in C++?|= and <> (invalid operators)|== and > (equal-to and greater-than)|EQUALS and GREATER (not valid)|B|C++ uses == for equality, != for not-equal, < > <= >= for comparisons, && for AND, || for OR.
DS|What does an if statement fundamentally allow a program to do?|Execute code conditionally based on a boolean condition|Create infinite loops|Merge and sort datasets|A|An if statement evaluates a condition — if true, the block executes; otherwise it is skipped. This is the foundation of decision-making.
DS|What three parts does a for loop require?|Exit condition only|Entry point only|Initialization, condition check, and increment/decrement|C|for(init; condition; update) — all three work together: initialize once, check before each iteration, update after each iteration.
DS|What is the primary reason to use nested loops in C++?|To improve overall performance|To process multi-dimensional data (e.g. 2D arrays and matrices)|To simplify single-loop logic|B|Nested loops allow you to iterate over rows and columns simultaneously — essential for 2D arrays and matrix operations.
DS|Which syntax correctly reads a value from the keyboard into a variable?|cin << myVar;|myVar >> cin;|cin >> myVar;|C|cin >> myVar; is the correct extraction syntax. The >> operator flows data FROM cin INTO the variable.
DS|Which C++ data type stores exactly ONE character?|int|char|string|B|char stores a single character (1 byte), like 'A' or '9'. string stores text of any length. int stores whole numbers.
DS|What does the % (modulus) operator return?|The quotient of integer division|The remainder after integer division|The absolute value of the result|B|10 % 3 = 1 (because 10 = 3×3 + 1). Used to check even/odd: if(n%2==0) → even.
DS|What is the output of: cout << 7 + 3 * 2;|20|13|17|B|Operator precedence: * runs before +. So 3*2=6 first, then 7+6=13. Use parentheses to override: (7+3)*2=20.
DS|Which function reads an entire line of text including spaces?|cin >> str|getline(cin, str)|cin.getline()|B|cin >> stops at whitespace — only reads one word. getline(cin, str) reads until Enter is pressed, capturing spaces.
DS|What does ceil(4.1) return?|4|5|4.1|B|ceil() always rounds UP to the nearest integer. ceil(4.1)=5, ceil(4.9)=5, ceil(-4.1)=-4. Opposite: floor() rounds DOWN.
DS|What is the index of the FIRST element in a C++ array?|1|0|-1|B|C++ arrays use zero-based indexing. int arr[5]: arr[0] is first, arr[4] is last. arr[5] is OUT OF BOUNDS.
DS|In recursion, what prevents the function from calling itself infinitely?|A loop counter variable|A base case — a condition that stops recursion|A void return type|B|Every recursive function MUST have a base case. Without it: infinite recursion → Stack Overflow crash! Example: if(n<=1) return 1;
DS|What does the * operator do when used with a pointer variable?|Multiplies the pointer by a value|Dereferences the pointer — accesses the value stored at that memory address|Declares a new pointer variable|B|int x=42; int* p=&x; cout<<p; prints the address. cout<<*p; DEREFERENCES → prints 42. & gets address; * gets value.
DS|Which C++ keyword allocates memory dynamically on the HEAP?|malloc|alloc|new|C|int* p = new int; allocates on the HEAP. You MUST free it manually: delete p; Stack: automatic (int x=5). Heap: manual (new/delete).
DS|A reference variable in C++ is best described as:|A complete copy of the original variable|An alias — another name for the SAME memory location|A pointer that cannot be NULL|B|int a=10; int& b=a; — b is NOT a copy. Both a and b share the exact same address. Changing b also changes a.
DS|In a Singly Linked List, each node contains:|Only the data value|The data value and a pointer to the next node|An index, data value, and a pointer|B|struct Node { int data; Node* next; }; — data holds the value, next holds the address of the next node (NULL if last).
DS|To insert a new node at the BEGINNING of a Linked List, you should:|Traverse all the way to the end first|Set newNode->next = head, then update head = newNode|Delete the current head node first|B|newNode->next = head; head = newNode; — This is O(1), constant time. No traversal needed for beginning insertion.
DS|Compared to arrays, Linked Lists have a significant advantage in:|Random access by index (e.g. arr[i])|Inserting and deleting elements — O(1) relink vs O(n) shift|Using less total memory per element|B|Array insert/delete: O(n) — must shift elements. Linked List insert/delete: O(1) — just relink pointers. But array access is O(1) vs LL O(n).
DS|What does sort(arr, arr+5) do to the array arr?|Sorts only the first element|Sorts the first 5 elements of arr in ascending order|Returns a new sorted copy of arr|B|#include<algorithm> required. arr is starting address, arr+5 is one past the end. Result: arr[0..4] sorted smallest to largest, in-place.
DS|Given: enum Day{Mon=1, Tue, Wed}; What is the value of Wed?|1|2|3|C|Mon is assigned 1 explicitly. Tue auto-increments to 2. Wed auto-increments to 3. Rule: once assigned, subsequent values increment by 1.
`;
