const dsQuestionsData = `
DS|Header files like <iostream> add functionality to C++ programs.|True|False|Cannot be determined|A|#include <iostream> is a preprocessor directive that attaches the standard I/O library before compilation, enabling cout and cin.
DS|The cout object outputs values and prints text to the screen.|True|False|Cannot be determined|A|cout (combined with <<) is the standard output stream object — it sends data to the console.
DS|Variables in C++ can store different data types like int, char, and string.|True|False|Cannot be determined|A|C++ is statically typed but provides many types: int, double, char, bool, string — each for a different kind of data.
DS|Constants are variables that can be changed during program execution.|True|False|Cannot be determined|B|Constants declared with 'const' are FIXED — attempting to change them causes a compile-time error. Example: const int MAX = 100;
DS|cin allows user input from the keyboard into a C++ program.|True|False|Cannot be determined|A|cin (with >>) is the standard input stream. It reads values typed by the user and stores them in variables.
DS|A const variable in C++ can be modified after its declaration.|True|False|Cannot be determined|B|const means the value is FIXED at initialization. Any attempt to modify it results in a compile error: cannot assign to variable with const-qualified type.
DS|cin >> can read a string that includes spaces between words.|True|False|Cannot be determined|B|FALSE — cin >> stops at the first whitespace. To read a full line including spaces, use getline(cin, str) instead.
DS|What does #include <iostream> enable in a C++ program?|Input/output capabilities (cout, cin)|Math functions like sqrt and pow|File handling operations|A|#include <iostream> attaches the I/O stream library which provides cout (output) and cin (input) — essential for any C++ program.
DS|What is the purpose of 'using namespace std;' in C++?|Allows use of standard library names without std:: prefix|Defines a new project namespace|Links the standard template library|A|Without it you would write std::cout and std::cin. The directive lets you write cout and cin directly.
DS|Which of the following is NOT a valid C++ variable type?|int|double|text|C|text is not a C++ keyword. Valid types include int, double, char, bool, string. 'text' would cause a compilation error.
DS|Which C++ data type stores exactly ONE character?|int|char|string|B|char stores a single character (1 byte), like 'A' or '9'. string stores text of any length. int stores whole numbers.
DS|Which syntax correctly prints the value of a variable in C++?|print(myVar)|cout << myVar|console.log(myVar)|B|cout << myVar is the correct C++ output syntax. print() is Python; console.log() is JavaScript.
DS|How do you read user input from the keyboard into a variable in C++?|var input = getInput()|cin >> myVar|myVar << cin|B|cin >> myVar reads from standard input. The >> operator extracts the value and stores it in myVar.
DS|Which function reads an entire line of text including spaces?|cin >> str|getline(cin, str)|cin.getline()|B|cin >> stops at whitespace — only reads one word. getline(cin, str) reads until Enter is pressed, capturing spaces.
DS|Which of the following are valid comparison/logical operators in C++?|= and <> (invalid operators)|== and > (equal-to and greater-than)|EQUALS and GREATER (not valid)|B|C++ uses == for equality, != for not-equal, < > <= >= for comparisons, && for AND, || for OR.
DS|sqrt() and other math functions are available in C++ without including any library.|True|False|Cannot be determined|B|FALSE — #include <cmath> is REQUIRED for sqrt(), pow(), abs(), round(), ceil(), floor(), max(), and min().
DS|What does the % (modulus) operator return?|The quotient of integer division|The remainder after integer division|The absolute value of the result|B|10 % 3 = 1 (because 10 = 3×3 + 1). Used to check even/odd: if(n%2==0) → even.
DS|What is the output of: cout << 7 + 3 * 2;|20|13|17|B|Operator precedence: * runs before +. So 3*2=6 first, then 7+6=13. Use parentheses to override: (7+3)*2=20.
DS|What does ceil(4.1) return?|4|5|4.1|B|ceil() always rounds UP to the nearest integer. ceil(4.1)=5, ceil(4.9)=5, ceil(-4.1)=-4. Opposite: floor() rounds DOWN.
DS|Which library package provides sort(), max_element(), and min_element() in C++?|iostream|cmath|algorithm|C|#include <algorithm> provides sort, max_element, min_element, reverse, find, and many other useful functions.
DS|An if statement specifies a block of code to execute when a condition is true.|True|False|Cannot be determined|A|if(condition) { ... } — the block only executes when the boolean condition evaluates to true.
DS|else if allows you to check additional conditions if previous ones are false.|True|False|Cannot be determined|A|else if chains let you test multiple mutually exclusive conditions sequentially — only the first true branch runs.
DS|for loops execute a block of code as long as a condition is true.|True|False|Cannot be determined|B|FALSE — for loops repeat a known, fixed number of iterations. It is the WHILE loop that repeats as long as a condition is true.
DS|Nested loops place a loop inside another loop.|True|False|Cannot be determined|A|A nested loop has an inner loop that completes all its iterations for every single iteration of the outer loop. Common for 2D arrays.
DS|The insertion operator << outputs values; the extraction operator >> gets user input.|True|False|Cannot be determined|A|cout << val sends output; cin >> var receives input. The direction of the arrows shows data flow direction.
DS|The for loop is the best choice when you know the exact number of iterations in advance.|True|False|Cannot be determined|A|for(int i=0; i<n; i++) is designed for a known count. Use while when the number of iterations is unknown or condition-driven.
DS|What does an if statement fundamentally allow a program to do?|Execute code conditionally based on a boolean condition|Create infinite loops|Merge and sort datasets|A|An if statement evaluates a condition — if true, the block executes; otherwise it is skipped. This is the foundation of decision-making.
DS|What three parts does a for loop require?|Exit condition only|Entry point only|Initialization, condition check, and increment/decrement|C|for(init; condition; update) — all three work together: initialize once, check before each iteration, update after each iteration.
DS|What is the primary reason to use nested loops in C++?|To improve overall performance|To process multi-dimensional data (e.g. 2D arrays and matrices)|To simplify single-loop logic|B|Nested loops allow you to iterate over rows and columns simultaneously — essential for 2D arrays and matrix operations.
DS|C++ arrays use zero-based indexing — the first element is at index 0.|True|False|Cannot be determined|A|int arr[5] has valid indices 0,1,2,3,4. Accessing arr[5] is out of bounds and causes undefined behavior.
DS|What is the index of the FIRST element in a C++ array?|1|0|-1|B|C++ arrays use zero-based indexing. int arr[5]: arr[0] is first, arr[4] is last. arr[5] is OUT OF BOUNDS.
DS|What is the time complexity of accessing an element by index in an array?|O(n)|O(log n)|O(1)|C|Arrays store elements in contiguous memory. The index directly calculates the address (base + offset), so access is always O(1).
DS|In C++, what does arr[i] translate to in pointer arithmetic?|arr - i|*(arr + i)|arr * i|B|Array indexing is syntactic sugar for pointer arithmetic. arr[i] is exactly equivalent to *(arr + i).
DS|A reference and a pointer in C++ are exactly the same thing.|True|False|Cannot be determined|B|References (int& b=a) are aliases — always bound to one variable, no NULL, no arithmetic. Pointers store addresses and can be NULL, reassigned, and incremented.
DS|Memory allocated with 'new' is automatically freed when the function returns.|True|False|Cannot be determined|B|HEAP memory (new) is MANUALLY managed — you must call delete or delete[]. Stack memory (int x=5) is freed automatically.
DS|What does the * operator do when used with a pointer variable?|Multiplies the pointer by a value|Dereferences the pointer — accesses the value stored at that memory address|Declares a new pointer variable|B|int x=42; int* p=&x; cout<<p; prints the address. cout<<*p; DEREFERENCES → prints 42. & gets address; * gets value.
DS|A reference variable in C++ is best described as:|A complete copy of the original variable|An alias — another name for the SAME memory location|A pointer that cannot be NULL|B|int a=10; int& b=a; — b is NOT a copy. Both a and b share the exact same address. Changing b also changes a.
DS|Dynamic memory allocation in C++ uses which pair of keywords?|malloc / free|new / delete|alloc / dealloc|B|int* p = new int[n]; allocates n integers on the heap. delete[] p; releases the memory. Always pair them to prevent memory leaks.
DS|What happens if you forget to call delete after using new in C++?|Compile error|Memory leak — the heap memory is never freed|Segmentation fault immediately|B|Memory leak: the allocated heap memory is never released. The program holds memory it can no longer use, wasting RAM over time.
DS|In recursion, what prevents the function from calling itself infinitely?|A loop counter variable|A base case — a condition that stops recursion|A void return type|B|Every recursive function MUST have a base case. Without it: infinite recursion → Stack Overflow crash! Example: if(n<=1) return 1;
DS|What is the space complexity of a recursive factorial function factorial(n)?|O(1)|O(n)|O(n²)|B|Each recursive call adds a new stack frame. factorial(n) makes n recursive calls, so n frames are active at once = O(n) space.
DS|What does sort(arr, arr+5) do to the array arr?|Sorts only the first element|Sorts the first 5 elements of arr in ascending order|Returns a new sorted copy of arr|B|#include<algorithm> required. arr is starting address, arr+5 is one past the end. Result: arr[0..4] sorted smallest to largest, in-place.
DS|In a Linked List, the last node's 'next' pointer must be set to NULL.|True|False|Cannot be determined|A|NULL marks the END of the list. The traversal loop while(temp != NULL) uses this to know when to stop.
DS|In a Singly Linked List, each node contains:|Only the data value|The data value and a pointer to the next node|An index, data value, and a pointer|B|struct Node { int data; Node* next; }; — data holds the value, next holds the address of the next node (NULL if last).
DS|To insert a new node at the BEGINNING of a Linked List, you should:|Traverse all the way to the end first|Set newNode->next = head, then update head = newNode|Delete the current head node first|B|newNode->next = head; head = newNode; — This is O(1), constant time. No traversal needed for beginning insertion.
DS|Compared to arrays, Linked Lists have a significant advantage in:|Random access by index (e.g. arr[i])|Inserting and deleting elements — O(1) relink vs O(n) shift|Using less total memory per element|B|Array insert/delete: O(n) — must shift elements. Linked List insert/delete: O(1) — just relink pointers. But array access is O(1) vs LL O(n).
DS|What is the time complexity of accessing an element by index in a Linked List?|O(1)|O(log n)|O(n)|C|Linked List nodes are scattered in memory. To reach index i, you must traverse from head one node at a time = O(n).
DS|What does NULL represent in a Linked List node's next pointer?|The beginning of the list|The end of the list — no more nodes|The middle of the list|B|When next == NULL, it signals the LAST node. The traversal loop while(temp != NULL) stops at this node.
DS|What is a Circular Linked List?|A list whose elements are sorted in a circle|The last node's next pointer points back to head|A doubly-linked list where both ends connect|B|In a Circular Linked List, the tail node's next points to head instead of NULL, creating a loop with no end.
DS|In a Doubly Linked List, each node contains:|Only a next pointer|A next pointer and a previous pointer|Only a previous pointer|B|struct Node { int data; Node* next; Node* prev; }; — allows traversal in BOTH directions (forward and backward).
DS|A Stack follows which principle?|FIFO — First In, First Out|LIFO — Last In, First Out|Random Access|B|Stack = LIFO. Think of a stack of plates — you always add and remove from the TOP. Last plate placed is first removed.
DS|Which data structure uses 'push' and 'pop' operations?|Queue|Stack|Linked List|B|Stack: push() adds to the top, pop() removes from the top. Both are O(1) and follow LIFO order.
DS|A Queue follows which principle?|LIFO — Last In, First Out|FIFO — First In, First Out|Random Access|B|Queue = FIFO. Think of a checkout line — the first person to join is the first to be served.
DS|Which data structure uses 'enqueue' and 'dequeue' operations?|Stack|Queue|Array|B|Queue: enqueue() adds to the rear (back), dequeue() removes from the front. Models real-world queues like print spoolers.
DS|In a Binary Search Tree (BST), where are values smaller than the root stored?|Right subtree|Left subtree|Root only|B|BST property: left child < parent < right child. This rule applies recursively at every node, enabling O(log n) search.
DS|What is the height of a tree that contains only one node (the root)?|1|0|2|B|Height = number of edges on the longest path from root to a leaf. A single root node has NO edges below it, so height = 0.
DS|Which tree traversal visits nodes in the order: Left → Root → Right?|Pre-order|In-order|Post-order|B|In-order traversal of a BST always produces values in ascending sorted order — a key property used in sorting.
DS|Which tree traversal visits nodes in the order: Root → Left → Right?|Pre-order|In-order|Post-order|A|Pre-order visits the root FIRST, then the left subtree, then the right subtree. Used to copy or serialize a tree.
DS|Which of the following is NOT a linear data structure?|Array|Linked List|Binary Tree|C|Linear structures store elements sequentially: Array, Linked List, Stack, Queue. Non-linear: Tree, Graph — elements branch out.
DS|A Stack can be used to implement an Undo feature in applications.|True|False|Cannot be determined|A|The undo stack stores each action as a push; pressing Ctrl+Z pops the last action — classic LIFO use. Undo, redo, and browser back-buttons all rely on a Stack internally.
DS|Elements in a Stack can be removed from both the top AND the bottom.|True|False|Cannot be determined|B|FALSE — a Stack only allows insertion and removal from the TOP (LIFO). Removing from the bottom would violate LIFO — that is a Deque (double-ended queue), not a Stack.
DS|A Circular Queue eliminates the false-full problem of a regular linear queue.|True|False|Cannot be determined|A|In a linear queue, FRONT advances on each dequeue, leaving early slots unreachable even when capacity exists — a 'false full' state. Circular queues use (index+1)%SIZE to wrap around and reuse those slots.
DS|The isEmpty() function for an array-based Stack returns true when top == 0.|True|False|Cannot be determined|B|FALSE — top == 0 means ONE element exists at index 0. isEmpty() returns true when top == -1, the initialized sentinel before any push. Checking top == 0 would wrongly report non-empty on a one-element stack.
DS|A Queue can be used to implement Breadth-First Search (BFS) in a graph.|True|False|Cannot be determined|A|BFS explores nodes level by level — neighbours are enqueued at the rear and dequeued from the front, matching FIFO exactly. DFS uses a Stack (or recursion). BFS → Queue; DFS → Stack.
DS|Both push() and pop() stack operations have O(n) time complexity.|True|False|Cannot be determined|B|FALSE — push() and pop() are both O(1). They only operate on the top element with no traversal or shifting. O(n) would only occur if you searched for an element inside the stack.
DS|When dequeuing the last element from a linked-list Queue, both front and rear pointers must be set to nullptr.|True|False|Cannot be determined|A|When the queue becomes empty, both front AND rear must become nullptr. Leaving either as a dangling pointer to the deleted node corrupts future isEmpty() checks and enqueue/dequeue operations.
DS|A Priority Queue processes elements in strict FIFO order just like a regular Queue.|True|False|Cannot be determined|B|FALSE — a Priority Queue dequeues the highest-priority element first, regardless of insertion order. Strict FIFO (first-in, first-out) is the property of a regular Queue only.
DS|A binary tree with N nodes has exactly N–1 edges.|True|False|Cannot be determined|A|Every node except the root has exactly one incoming edge (from its parent). N nodes → N-1 edges. This is true for all trees, not just binary trees.
DS|In-order traversal of ANY binary tree always produces nodes in sorted (ascending) order.|True|False|Cannot be determined|B|FALSE — in-order (Left → Root → Right) of a BST produces sorted output because of the BST property. For an arbitrary binary tree with no ordering rule, in-order produces no particular order.
DS|The root node of a tree has a depth equal to 0.|True|False|Cannot be determined|A|Depth = number of edges from the root to that node. The root has no edges above it, so depth = 0. Its children have depth 1, their children depth 2, and so on.
DS|A complete binary tree is always a perfect binary tree.|True|False|Cannot be determined|B|FALSE — a complete binary tree fills all levels except possibly the last (filled left to right). A perfect binary tree has ALL levels completely filled. Every perfect tree is complete, but a complete tree with a non-full last level is not perfect.
DS|In the worst case, searching a BST has O(n) time complexity.|True|False|Cannot be determined|A|When all insertions are in sorted order, the BST degenerates into a linked list. Searching then requires traversing all N nodes = O(n). This is why balanced BSTs (AVL, Red-Black) guarantee O(log n) worst case.
DS|Deleting a leaf node from a BST requires no structural restructuring.|True|False|Cannot be determined|A|A leaf node has no children — simply set its parent's pointer to nullptr and free the node. No rotation or re-linking needed, unlike deleting a node with one or two children.
DS|Pre-order traversal visits the left subtree BEFORE visiting the root.|True|False|Cannot be determined|B|FALSE — Pre-order visits the ROOT first, then left, then right (Root → Left → Right). In-order (Left → Root → Right) visits the left subtree before the root.
DS|The in-order successor of a BST node is the smallest value in its right subtree.|True|False|Cannot be determined|A|The in-order successor is the next node in in-order sequence — always the leftmost (minimum) node in the right subtree. Used when deleting a two-child node to preserve BST ordering.
DS|Which Stack operation views the top element WITHOUT removing it?|push()|pop()|peek()|C|peek() (also called top()) returns the value at the top of the stack without modifying it. push() adds to the top, pop() removes from the top. All three are O(1).
DS|In a Queue, elements are added at ___ and removed from ___.|REAR / FRONT|FRONT / REAR|TOP / BOTTOM|A|Queue = FIFO. enqueue() adds to the REAR (back). dequeue() removes from the FRONT. This is opposite of a Stack where both operations happen at the top.
DS|What problem does the Circular Queue solve compared to a regular linear queue?|Slow enqueue performance|False-full problem — dequeued front slots become unreachable|Stack overflow errors|B|In a linear queue, FRONT advances on dequeue, leaving early slots unreachable even when array has space. Circular queues use (index+1)%SIZE to wrap around and reuse those slots.
DS|Calling pop() on an EMPTY Stack triggers which type of error?|OVERFLOW|Compile error|UNDERFLOW|C|Underflow occurs when you try to remove from an empty structure. Overflow occurs when you try to add to a full structure. Always check isEmpty() before calling pop() to prevent underflow.
DS|Which data structure is used INTERNALLY by the function call mechanism in C++?|Queue|Linked List|Stack|C|Every function call pushes a stack frame (local variables, return address) onto the call stack. Return pops it — classic LIFO. Infinite recursion exhausts this stack → Stack Overflow.
DS|A queue has capacity 5. After enqueue(A,B,C,D,E) then two dequeue() calls, what is the element at FRONT?|A|B|C|C|After enqueuing 5 items FRONT=A. First dequeue() removes A → FRONT=B. Second dequeue() removes B → FRONT=C. Queue now holds [C,D,E].
DS|Which C++ header file provides the std::stack class?|#include &lt;queue&gt;|#include &lt;stack&gt;|#include &lt;deque&gt;|B|#include<stack> provides std::stack<T>. #include<queue> provides std::queue<T> and std::priority_queue<T>. Both are part of the C++ Standard Template Library (STL).
DS|What is the MAXIMUM number of nodes in a binary tree of height 3?|7|15|8|B|A perfect binary tree of height h has 2^(h+1)-1 nodes. Height 3: 2^4-1=15. Level 0:1 node, Level 1:2, Level 2:4, Level 3:8. Total=15 nodes.
DS|Which tree traversal produces a PREFIX (Polish notation) expression?|In-order — Left Root Right|Post-order — Left Right Root|Pre-order — Root Left Right|C|Pre-order visits Root first → generates prefix notation (operator before operands). In-order → infix. Post-order → postfix (RPN). Prefix: +AB | Infix: A+B | Postfix: AB+
DS|When deleting a BST node that has TWO children, what value replaces the deleted node?|Left child value|Right child value|In-order successor (smallest in right subtree)|C|The in-order successor — leftmost node of the right subtree — replaces the deleted node. It is the smallest value greater than the deleted node, preserving the BST property at every position.
DS|What does an uninitialized int arr[5] declaration contain in C++?|All zeros — auto-initialized|Random garbage values from previous memory|nullptr pointers|B|Stack-allocated C arrays are NOT automatically initialized. They contain whatever bytes were previously at those RAM addresses. Use int arr[5]={0}; or int arr[5]={}; to guarantee zeros.
DS|What does sizeof(arr)/sizeof(arr[0]) calculate when used in the array's own scope?|Index of the last element|Total bytes used by the array|Number of elements in the array|C|sizeof(arr)=total bytes. sizeof(arr[0])=bytes per element (4 for int). Division gives element count. CRITICAL: only works in direct scope — inside functions sizeof(arr)=pointer size (8 bytes), not array size!
`;
